landscapeName: ospo
landscapeMemberClasses:
   - name: General Membership
     category: General
project: a0941000002wBzFAAU # TODO Group
landscapeMemberCategory: TODO Group Member
landscapefile: landscape.yml
missingcsvfile: missing.csv
